### ISSUE TITLE
Submit Button Not Styled

### ISSUE THREAD

**Issue by Deadmano** [cybertec-postgresql/rjsf-material-ui#23]
I'm using a default installation of `react-jsonschema-form`, version `1.7.0` as well as version `0.3.4` of `rjsf-material-ui` from NPM. For some reason the `send` button in the form is not styled, and inspect the element reveals it is still use the default bootstrap classes.

Is there something I am missing here? My entire form is:

```
<Form
        schema={Mission}
        onChange={log('changed')}
        onSubmit={log('submitted')}
        onError={log('errors')}
/>
```

This is what it looks like:

![Issue](https://i.imgur.com/YGHrTNY.png)

**Comment by agustin107** [comment]
Hi @Deadmano, thanks for your first issue.

That happens because if the form doesn't have buttons as children, print the default button.
https://github.com/mozilla-services/react-jsonschema-form/blob/d7b26fb9d993f419217fd5eb11381a01f70e24e5/src/components/Form.js#L351

You have to define your custom form button like here https://github.com/cybertec-postgresql/rjsf-material-ui/blob/be021b9ff54aeb65120b850195cf3a4aa9ce3756/example/src/body/Example.tsx#L135

**Comment by agustin107** [comment]
I was looking if we could rewrite the default button with a custom widget or field component, but this isn't possible :/

**Comment by agentmilindu** [comment]
@agustin107 I feel like this needs to be documented somewhere. Do you have any documentation where I can contribute to?
